version: "3.9"
services:

  postgres:
    image: postgres
    environment:
#      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - postgres
  app:
    build:
      context: .
      args:
        APP_PORT: "8000"
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - .env
    networks:
      - postgres

volumes:
  postgres-db:

networks:
  postgres:
    driver: bridge