"""init

Revision ID: 2c887c4c50da
Revises: 
Create Date: 2023-06-15 16:48:21.053263

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2c887c4c50da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('about_me', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('datetime_login', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('user_id_one', sa.Integer(), nullable=False),
    sa.Column('user_id_two', sa.Integer(), nullable=False),
    sa.Column('id_friendships', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_one'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id_two'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_friendships'),
    sa.UniqueConstraint('user_id_one', 'user_id_two', name='unique_1_2')
    )
    op.create_index(op.f('ix_friendships_user_id_one'), 'friendships', ['user_id_one'], unique=False)
    op.create_index(op.f('ix_friendships_user_id_two'), 'friendships', ['user_id_two'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendships_user_id_two'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_user_id_one'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_table('user')
    # ### end Alembic commands ###
